// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mes_covariance_em
Rcpp::List mes_covariance_em(const arma::mat& beta, const arma::mat& se2, arma::mat V, const arma::mat& prior, Rcpp::List configs, int maxiter, double tol);
RcppExport SEXP _MESuSiE_mes_covariance_em(SEXP betaSEXP, SEXP se2SEXP, SEXP VSEXP, SEXP priorSEXP, SEXP configsSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type se2(se2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type configs(configsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(mes_covariance_em(beta, se2, V, prior, configs, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// loglik_cpp
double loglik_cpp(arma::vec V, const arma::mat& betahat, const arma::mat& shat2, const arma::mat& prior_weight, const int nancestry, arma::uvec diag_index, Rcpp::List config_list);
RcppExport SEXP _MESuSiE_loglik_cpp(SEXP VSEXP, SEXP betahatSEXP, SEXP shat2SEXP, SEXP prior_weightSEXP, SEXP nancestrySEXP, SEXP diag_indexSEXP, SEXP config_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type shat2(shat2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior_weight(prior_weightSEXP);
    Rcpp::traits::input_parameter< const int >::type nancestry(nancestrySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type diag_index(diag_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config_list(config_listSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_cpp(V, betahat, shat2, prior_weight, nancestry, diag_index, config_list));
    return rcpp_result_gen;
END_RCPP
}
// mvlmm_reg
SEXP mvlmm_reg(arma::mat betahat, arma::mat shat2, arma::mat V_mat);
RcppExport SEXP _MESuSiE_mvlmm_reg(SEXP betahatSEXP, SEXP shat2SEXP, SEXP V_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type betahat(betahatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type shat2(shat2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V_mat(V_matSEXP);
    rcpp_result_gen = Rcpp::wrap(mvlmm_reg(betahat, shat2, V_mat));
    return rcpp_result_gen;
END_RCPP
}
// mes_stable_mvlmm
Rcpp::List mes_stable_mvlmm(const arma::mat& beta, const arma::mat& se2, const arma::mat& V);
RcppExport SEXP _MESuSiE_mes_stable_mvlmm(SEXP betaSEXP, SEXP se2SEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type se2(se2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(mes_stable_mvlmm(beta, se2, V));
    return rcpp_result_gen;
END_RCPP
}
// mes_stable_loglik
double mes_stable_loglik(const arma::mat& beta, const arma::mat& se2, const arma::mat& V, const arma::mat& prior, Rcpp::List configs);
RcppExport SEXP _MESuSiE_mes_stable_loglik(SEXP betaSEXP, SEXP se2SEXP, SEXP VSEXP, SEXP priorSEXP, SEXP configsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type se2(se2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type configs(configsSEXP);
    rcpp_result_gen = Rcpp::wrap(mes_stable_loglik(beta, se2, V, prior, configs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MESuSiE_mes_covariance_em", (DL_FUNC) &_MESuSiE_mes_covariance_em, 7},
    {"_MESuSiE_loglik_cpp", (DL_FUNC) &_MESuSiE_loglik_cpp, 7},
    {"_MESuSiE_mvlmm_reg", (DL_FUNC) &_MESuSiE_mvlmm_reg, 3},
    {"_MESuSiE_mes_stable_mvlmm", (DL_FUNC) &_MESuSiE_mes_stable_mvlmm, 3},
    {"_MESuSiE_mes_stable_loglik", (DL_FUNC) &_MESuSiE_mes_stable_loglik, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MESuSiE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
