# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mes_covariance_em <- function(beta, se2, V, prior, configs, maxiter = 100L, tol = 1e-9) {
    .Call(`_MESuSiE_mes_covariance_em`, beta, se2, V, prior, configs, maxiter, tol)
}

loglik_cpp <- function(V, betahat, shat2, prior_weight, nancestry, diag_index, config_list) {
    .Call(`_MESuSiE_loglik_cpp`, V, betahat, shat2, prior_weight, nancestry, diag_index, config_list)
}

mvlmm_reg <- function(betahat, shat2, V_mat) {
    .Call(`_MESuSiE_mvlmm_reg`, betahat, shat2, V_mat)
}

mes_stable_mvlmm <- function(beta, se2, V) {
    .Call(`_MESuSiE_mes_stable_mvlmm`, beta, se2, V)
}

mes_stable_loglik <- function(beta, se2, V, prior, configs) {
    .Call(`_MESuSiE_mes_stable_loglik`, beta, se2, V, prior, configs)
}

